#!/usr/bin/env python3

import sys
import subprocess

from util import get_site, get_github_user_and_repo, get_origin_url

def main():
	origin_url = get_origin_url()
	site       = get_site(origin_url)
	if site == "github.com":
		user, repo = get_github_user_and_repo(origin_url)
		url        = "https://github.com/%s/%s/issues?utf8=%%E2%%9C%%93&q=" % (user, repo)
	elif site == "chromium.googlesource.com":
		project    = origin_url.replace("https://chromium.googlesource.com/", "", 1).split("/")[0]
		url        = "https://bugs.chromium.org/p/%s/issues/list?q=" % (project)

	subprocess.call(["xdg-open", url])

if __name__ == "__main__":
	main()
