#!/usr/bin/python -SB

from __future__ import print_function

import sys
import subprocess

from util import get_site, get_github_user_and_repo, get_origin_url

def main():
	commit     = sys.argv[1]
	origin_url = get_origin_url()
	site       = get_site(origin_url)
	if site == "github":
		user, repo = get_github_user_and_repo(origin_url)
		url        = b"https://github.com/%s/%s/commit/%s" % (user, repo, commit)
	elif site == "kernel.ubuntu.com":
		repo_path  = origin_url.replace("git://kernel.ubuntu.com/", "", 1)
		url        = b"http://kernel.ubuntu.com/git/%s/commit/?id=%s" % (repo_path, commit)

	subprocess.call([b"xdg-open", url])

if __name__ == "__main__":
	main()
