#!/usr/bin/python -SB

from __future__ import print_function

import sys
import subprocess

from util import get_site, get_github_user_and_repo, get_origin_url

def main():
	commit     = sys.argv[1]
	origin_url = get_origin_url()
	site       = get_site(origin_url)
	if site == "github.com":
		user, repo = get_github_user_and_repo(origin_url)
		url        = b"https://github.com/%s/%s/commit/%s" % (user, repo, commit)
	elif site == "kernel.ubuntu.com":
		repo_path  = origin_url.replace(b"git://kernel.ubuntu.com/", b"", 1)
		url        = b"http://kernel.ubuntu.com/git/%s/commit/?id=%s" % (repo_path, commit)
	elif site == "anonscm.debian.org":
		repo_path  = origin_url.replace(b"https://anonscm.debian.org/git/", b"", 1)
		url        = b"https://anonscm.debian.org/git/%s/commit/?id=%s" % (repo_path, commit)
	elif site == "chromium.googlesource.com":
		repo_path  = origin_url.replace(b"https://chromium.googlesource.com/", b"", 1).rstrip(b"/")
		url        = b"https://chromium.googlesource.com/%s/+/%s" % (repo_path, commit)

	subprocess.call([b"xdg-open", url])

if __name__ == "__main__":
	main()
